### ISSUE TITLE
Include commit co-authors when releasing

### ISSUE THREAD

**Issue by santisoler** [fatiando/.github#19]
On the issue template for releases, one of the items from the check list asks maintainers to list all the people that made contributions since last release by running `git shortlog HEAD...v1.2.3 -sne`.

This output of `git log` doesn't include Co-authors. We should include a line that gets coauthors as well.

**Comment by leouieda** [comment]
Ah good idea. I hadn't realized that. This entire process should probably be automated to large extent. Maybe one day when someone is bored and looking to code.
